# Local Development Chain
[local]
endpoint_url = "${LOCAL_RPC_URL}"

[local.uint]
chain_id = 1337

[local.string]
gas_denom = "eth"
explorer_url = "http://localhost:8545"
cosmos_chain_id = "local-1"

# MANTRA Mainnet Configuration
[mantra_mainnet]
endpoint_url = "${MANTRA_MAINNET_RPC_URL}"

[mantra_mainnet.address]
hsc = "0x0000F90827F1C53a10cb7A02335B175320002935"
create2 = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
createx = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
multicall3 = "0xcA11bde05977b3631167028862bE2a173976CA11"
wrapped_om = "0xE3047710EF6cB36Bcf1E58145529778eA7Cb5598"

[mantra_mainnet.uint]
chain_id = 5888

[mantra_mainnet.string]
gas_denom = "uom"
explorer_url = "https://blockscout.mantrascan.io"
blockscout_api_url = "https://blockscout.mantrascan.io/api"
cosmos_chain_id = "mantra-1"
cosmos_api = "https://api.mantrachain.io"
cosmos_rpc = "https://rpc.mantrachain.io"

# MANTRA Dukong Testnet Configuration
[mantra_dukong]
endpoint_url = "${MANTRA_DUKONG_RPC_URL}"

[mantra_dukong.address]
hsc = "0x0000F90827F1C53a10cb7A02335B175320002935"
create2 = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
createx = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
multicall3 = "0xcA11bde05977b3631167028862bE2a173976CA11"
wrapped_om = "0x10d26F0491fA11c5853ED7C1f9817b098317DC46"

[mantra_dukong.uint]
chain_id = 5887

[mantra_dukong.string]
gas_denom = "uom"
explorer_url = "https://explorer.dukong.io"
blockscout_api_url = "https://explorer.dukong.io/api"
cosmos_chain_id = "mantra-dukong-1"
cosmos_api = "https://api.dukong.mantrachain.io"
cosmos_rpc = "https://rpc.dukong.mantrachain.io"
faucet_url = "https://faucet.dukong.mantrachain.io"
